apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    name: nginx-svc
spec:
  ports:
    # the port that this service should serve on
    - port: 8081
      targetPort: 8081
  selector:
    name: nginx-svc

