apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 40Mi
  hostPath:
    path: /home/pavelnemoi/code/tmp/k8s
