apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  volumeName: volume-1
  resources:
    requests:
      storage: 40Mi
